name: Macros
on: [push, pull_request, workflow_dispatch]
jobs:
  install:
    name: Install
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
    strategy:
      fail-fast: false
      matrix:
        ocaml-compiler: [ 'ocaml-variants.4.04.0+macros' ]
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            macros: file:///home/runner/work/modular-macros-opam/modular-macros-opam
          dune-cache: false
          opam-depext: false

      - name: Deps
        run: |
          opam install --yes ocamlfind
          opam install --yes `ls packages | grep -v ocaml-variants`
